<?php
declare(strict_types=1);
require __DIR__.'/lib.php';
try { config();auth_start(); } catch(Throwable $e){http_response_code(503);exit('Analytics storage is unavailable.');}
$error='';
if ($_SERVER['REQUEST_METHOD']==='POST') {
    if(!hash_equals($_SESSION['csrf'],(string)($_POST['csrf']??''))){http_response_code(403);exit('Reload this page and try again.');}
    if(isset($_POST['logout'])){$_SESSION=[];session_destroy();header('Location: ./');exit;}
    if(!limit('login',10,900)){$error='Too many attempts. Try again in 15 minutes.';http_response_code(429);}
    elseif(password_verify(substr((string)($_POST['password']??''),0,256),config()['password_hash'])){
        session_regenerate_id(true);$_SESSION['authenticated_until']=time()+8*3600;$_SESSION['csrf']=bin2hex(random_bytes(24));header('Location: ./');exit;
    }else{$error='Password not recognised.';http_response_code(401);}
}
?><!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>VERTIGO · Private analytics</title><link rel="stylesheet" href="style.css"><body>
<main><header><div><p class="eyebrow">ALPHA SQUARED GAMES · OWNER ACCESS</p><h1>VERTIGO <span>Observatory</span></h1></div><span class="badge">PRIVATE</span></header>
<?php if(!authenticated()): ?>
<section class="login"><p class="eyebrow">GAMEPLAY ANALYTICS</p><h2>See what happens on the tower.</h2><p>Sign in to view player counts, progress and completion data.</p>
<form method="post"><input type="hidden" name="csrf" value="<?=e($_SESSION['csrf'])?>"><label for="password">Dashboard password</label><input id="password" name="password" type="password" autocomplete="current-password" required autofocus><button>Sign in</button></form>
<p class="error" role="alert"><?=e($error)?></p><small>The dashboard and its exports require authentication.</small></section>
<?php else:
 $range=in_array($_GET['range']??'all',['all','today','7','30'],true)?($_GET['range']??'all'):'all';$tests=($_GET['tests']??'0')==='1';
 try{$r=report($range,$tests);}catch(Throwable $e){http_response_code(503);exit('Cannot read analytics. No totals are shown to avoid reporting incomplete data.');}
 $m=$r['totals'];$plays=$m['plays'];$fmt=fn($n)=>number_format((float)$n, $n==floor($n)?0:1);$rate=$plays?round(100*$m['completions']/$plays,1):0;
?>
<nav><form method="get"><label for="range">Period</label><select name="range" id="range"><?php foreach(['all'=>'All time','today'=>'Today (UTC)','7'=>'Last 7 days','30'=>'Last 30 days'] as $v=>$label):?><option value="<?=e($v)?>" <?=$range===$v?'selected':''?>><?=e($label)?></option><?php endforeach;?></select><label><input type="checkbox" name="tests" value="1" <?=$tests?'checked':''?>> Debug / QA only</label><button>Refresh</button></form><div class="exports"><a href="export.php?format=json&amp;range=<?=e($range)?>&amp;tests=<?=$tests?1:0?>">JSON export</a><a href="export.php?format=csv&amp;range=<?=e($range)?>&amp;tests=<?=$tests?1:0?>">CSV export</a><form method="post"><input type="hidden" name="csrf" value="<?=e($_SESSION['csrf'])?>"><button name="logout" value="1" class="quiet">Sign out</button></form></div></nav>
<p class="status">Updated <?=e(gmdate('Y-m-d H:i:s'))?> UTC · Tracking since <?=e($r['tracking_since']??'the first incoming visit')?> · <?=$tests?'Debug/QA data — excluded from player totals':'Normal play — debug sessions excluded'?></p>
<div class="cards">
<?php foreach([
 ['Unique players',$r['unique_players'],'Distinct anonymous browsers that pressed Begin'],['Total plays',$plays,'Each Begin / Continue starts a play session'],['Climb attempts',$m['climb_attempts'],'Entering the stairs, including retries after a fall'],['Climbed',$fmt($m['climbed_m']).' m','Upward stair movement; excludes jumps and teleports'],['Walked',$fmt($m['walked_m']).' m','Horizontal distance on the ground or stairs'],['Falls',$m['falls'],'Falls that sent a player to a checkpoint'],['Roof arrivals',$m['roof_arrivals'],'Times players reached the roof'],['Button presses',$m['button_presses'],'Roof action presses; successful activations below'],['Collapses started',$m['collapse_starts'],'The roof switch successfully activated'],['Finished collapses',$m['completions'],'Reached the ending screen'],['Completion rate',$rate.'%','Finished collapses ÷ plays; includes continues'],['Active play',round($m['active_seconds']/60,1).' min','Visible, unpaused gameplay, including the collapse']
] as [$label,$value,$detail]):?><article><p><?=e($label)?></p><strong><?=e(is_numeric($value)?$fmt($value):$value)?></strong><small><?=e($detail)?></small></article><?php endforeach;?>
</div>
<section><div class="sectionhead"><h2>Where players stop</h2><p>Last seen ≠ confirmed abandonment. A player may return later.</p></div><div class="tablewrap"><table><thead><tr><th>Lap</th><th>Plays reaching it</th><th>Falls after this lap</th><th>Last seen here*</th><th>Reach</th></tr></thead><tbody><?php foreach($r['laps'] as $i=>$lap):?><tr><td><?=$i+1?></td><td><?=$lap['reached']?></td><td><?=$lap['falls']?></td><td><?=$lap['last']?></td><td><meter min="0" max="<?=max(1,$plays)?>" value="<?=$lap['reached']?>"></meter></td></tr><?php endforeach;?></tbody></table></div><small>* Unfinished plays with no update for over two minutes. Falls are grouped by the last grounded stair lap, not an exact collision coordinate.</small></section>
<section><div class="sectionhead"><h2>Approximate player locations</h2><p>IP-based estimates · no browser location permission</p></div><div class="tablewrap"><table><thead><tr><th>Country</th><th>Region, when available</th><th>Unique browsers</th><th>Plays</th><th>Falls</th><th>Finished</th><th>Climbed</th></tr></thead><tbody><?php foreach($r['locations'] as $location):?><tr><td><?=e($location['country_name']??'Unknown')?></td><td><?=e($location['region']??'—')?></td><td><?=$fmt($location['unique_players'])?></td><td><?=$fmt($location['plays'])?></td><td><?=$fmt($location['falls'])?></td><td><?=$fmt($location['completions'])?></td><td><?=$fmt($location['climbed_m'])?> m</td></tr><?php endforeach;?></tbody></table></div><small>Estimated by the hosting server from the connection IP. VPNs, proxies and mobile networks can show another location. No raw IP, city or coordinates are stored in analytics. Older or unresolved visits appear as Unknown. A browser can appear in more than one location across visits. Location details are included in the private JSON export.</small></section>
<div class="columns"><section><h2>Mobile vs desktop</h2><div class="tablewrap"><table><thead><tr><th>Platform</th><th>Plays</th><th>Falls</th><th>Finished</th><th>Rate</th></tr></thead><tbody><?php foreach($r['platforms'] as $platform=>$p):?><tr><td><?=e(ucfirst($platform))?></td><td><?=$fmt($p['plays'])?></td><td><?=$fmt($p['falls'])?></td><td><?=$fmt($p['completions'])?></td><td><?=$p['plays']?round(100*$p['completions']/$p['plays'],1):0?>%</td></tr><?php endforeach;?></tbody></table></div></section>
<section><h2>Daily activity</h2><div class="tablewrap"><table><thead><tr><th>UTC start date</th><th>Plays</th><th>Falls</th><th>Finished</th></tr></thead><tbody><?php foreach(array_reverse($r['daily'],true) as $day=>$d):?><tr><td><?=e($day)?></td><td><?=$fmt($d['plays'])?></td><td><?=$fmt($d['falls'])?></td><td><?=$fmt($d['completions'])?></td></tr><?php endforeach;?></tbody></table></div></section></div>
<section><h2>More gameplay signals</h2><div class="signals"><?php foreach(['page_views'=>'Page visits','new_games'=>'New games','continues'=>'Continues','jumps'=>'Jumps','auto_jumps'=>'Assisted jumps','short_drops'=>'Nonfatal drops over 1.2 m','crumble_triggers'=>'Crumble warnings','slabs_broken'=>'Slabs broken','figure_grabs'=>'Creature grabs','nerve_stumbles'=>'Nerve stumbles','extinguishes'=>'Successful extinguishes','panic_seconds'=>'Seconds at low nerve'] as $k=>$label):?><div><span><?=e($label)?></span><b><?=$fmt($m[$k])?></b></div><?php endforeach;?><div><span>Average active frame rate</span><b><?=$m['active_seconds']?round($m['frames']/$m['active_seconds'],1):0?> fps</b></div><div><span>Frames slower than 50 ms</span><b><?=$m['frames']?round(100*$m['slow_frames']/$m['frames'],1):0?>%</b></div></div></section>
<section><h2>Recent plays <small>Latest 100 visits in this period</small></h2><div class="tablewrap"><table><thead><tr><th>Started (UTC)</th><th>Platform</th><th>Entry</th><th>Rough location</th><th>Climbed</th><th>Highest</th><th>Falls</th><th>Finished</th></tr></thead><tbody><?php foreach($r['recent'] as $s):?><tr><td><?=e($s['started'])?></td><td><?=e($s['platform'])?></td><td><?=e($s['kind'])?></td><td><?=e(implode(' · ',array_filter([$s['location']['country_name']??'Unknown',$s['location']['region']??null])))?></td><td><?=$fmt($s['meters'])?> m</td><td><?=$fmt($s['height'])?> m</td><td><?=$fmt($s['falls'])?></td><td><?=$s['completed']?'Yes':'—'?></td></tr><?php endforeach;?></tbody></table></div></section>
<footer><p>Unique players estimate browsers, not verified people. Clearing storage or using another browser creates a new identity. Updates arrive about every 15 seconds and at milestones; blockers, opt-outs, offline exits and abrupt browser termination can reduce counts. Earlier play cannot be reconstructed.</p><p>Periods group sessions by their start date. “Climbs” means attempts; roof arrivals and finished collapses measure success. Client-reported data is validated and rate-limited, but it is not fraud-proof. No public statistics endpoint is enabled.</p></footer>
<?php endif;?></main></body></html>
